auth:
  social_auth_google:
    route: social_auth_google.redirect_to_google
    img_path: modules/contrib/social_auth_google/img/google_logo.svg
post_login: /user
redirect_user_form: false
disable_admin_login: false
disabled_roles:
  site_viewer: '0'
  administrator: '0'
  content_editor: '0'
user_allowed: login
_core:
  default_config_hash: 0E8z47ONguVcapiw1PGWDRs6g0NRDCzrym4mP_jcELU
